# Generated by Django 3.2.8 on 2021-11-15 05:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Country')),
                ('isd', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(1)], verbose_name='ISD/Country Code')),
                ('mobile_no_digits', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(5)], verbose_name='Mobile Number digit')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='ISO Code')),
                ('timezone', models.CharField(blank=True, help_text='Please add correct country timezone.', max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', limit_choices_to=models.Q(('is_staff', 0), ('is_superuser', 0), _negated=True), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_countrymasters', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('currency', models.ForeignKey(blank=True, limit_choices_to={'is_active': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_master_currency', to='configuration.currencymaster', verbose_name='Currency')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', limit_choices_to=models.Q(('is_staff', 0), ('is_superuser', 0), _negated=True), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_countrymasters', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': '  Country Master',
                'verbose_name_plural': '  Country Master',
                'db_table': 'country_master',
            },
        ),
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('state', models.CharField(db_index=True, max_length=50, verbose_name='State')),
                ('country', models.ForeignKey(db_column='country', limit_choices_to={'is_active': '1'}, on_delete=django.db.models.deletion.CASCADE, to='location.countrymaster', verbose_name='Country Name')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', limit_choices_to=models.Q(('is_staff', 0), ('is_superuser', 0), _negated=True), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_statemasters', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', limit_choices_to=models.Q(('is_staff', 0), ('is_superuser', 0), _negated=True), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_statemasters', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': ' State Master',
                'verbose_name_plural': ' State Master',
                'db_table': 'state_master',
                'unique_together': {('country', 'state')},
            },
        ),
        migrations.CreateModel(
            name='CityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.CharField(db_index=True, max_length=50, verbose_name='City')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', limit_choices_to=models.Q(('is_staff', 0), ('is_superuser', 0), _negated=True), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_citymasters', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('state', models.ForeignKey(db_column='state', limit_choices_to={'is_active': '1'}, on_delete=django.db.models.deletion.CASCADE, to='location.statemaster', verbose_name='State Name')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', limit_choices_to=models.Q(('is_staff', 0), ('is_superuser', 0), _negated=True), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_citymasters', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'City Master',
                'verbose_name_plural': 'City Master',
                'db_table': 'city_master',
                'unique_together': {('state', 'city')},
            },
        ),
    ]
