# Generated by Django 3.2.8 on 2021-12-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20211202_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='is_same',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
