# Generated by Django 3.2.8 on 2021-11-15 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuration', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notification_main_type', models.CharField(max_length=100)),
                ('notification_type', models.CharField(max_length=100, verbose_name='Notification Type')),
                ('sample_content', models.TextField(verbose_name='Sample Content')),
                ('notification_category', models.CharField(blank=True, choices=[('PUSH', 'PUSH'), ('SMS', 'SMS'), ('EMAIL', 'EMAIL')], max_length=20, null=True, verbose_name='Notification Category')),
                ('notification_for', models.CharField(choices=[('customer', 'Customer'), ('both', 'Both'), ('admin', 'Admin')], max_length=50, verbose_name='Notification For')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', limit_choices_to=models.Q(('is_staff', 0), ('is_superuser', 0), _negated=True), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_notificationconfigurations', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.language')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', limit_choices_to=models.Q(('is_staff', 0), ('is_superuser', 0), _negated=True), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_notificationconfigurations', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': ' Notification Configuration',
                'verbose_name_plural': ' Notification Configuration',
                'db_table': 'notification_configuration',
            },
        ),
        migrations.CreateModel(
            name='NotificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notification_category', models.CharField(choices=[('PUSH', 'PUSH'), ('SMS', 'SMS'), ('EMAIL', 'EMAIL')], max_length=20, verbose_name='Notification Category')),
                ('notification_to', models.CharField(choices=[('customer', 'Customer'), ('both', 'Both'), ('admin', 'Admin')], max_length=50)),
                ('is_event_done', models.CharField(default='0', max_length=50)),
                ('reason_for_failed', models.TextField(blank=True, null=True, verbose_name='Reason For Non Delivery')),
                ('message_body', models.TextField(verbose_name='Notification Content')),
                ('device_type', models.CharField(blank=True, choices=[('ios', 'IOS'), ('android', 'ANDROID'), ('web', 'WEB')], max_length=20, null=True, verbose_name='Device Type')),
                ('is_read', models.BooleanField(default=False)),
                ('notify_at', models.DateTimeField(auto_now_add=True, verbose_name='Notification Date & Time')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', limit_choices_to=models.Q(('is_staff', 0), ('is_superuser', 0), _negated=True), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_notificationrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customerprofile', verbose_name='Customer')),
                ('notification_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notification.notificationconfiguration', verbose_name='Notification Type')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', limit_choices_to=models.Q(('is_staff', 0), ('is_superuser', 0), _negated=True), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_notificationrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Notification History',
                'verbose_name_plural': 'Notification History',
                'db_table': 'notification_record',
            },
        ),
        migrations.CreateModel(
            name='NotificationFirebaseToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('device_token', models.TextField(verbose_name='Fire base Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('device_type', models.CharField(choices=[('ios', 'IOS'), ('android', 'ANDROID'), ('web', 'WEB')], max_length=30, verbose_name='Device Type')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customerprofile')),
            ],
            options={
                'verbose_name': 'Notification Firebase',
                'verbose_name_plural': 'Notification Firebase',
            },
        ),
    ]
