# Generated by Django 3.2.8 on 2021-11-15 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_aboutus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='termsconditions',
            old_name='terms_condtions',
            new_name='terms_conditions',
        ),
    ]
