# Generated by Django 3.2.8 on 2021-11-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_rename_terms_condtions_termsconditions_terms_conditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='meta_title',
        ),
    ]
