# Generated by Django 3.2.8 on 2021-11-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_product_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('r', 'red'), ('y', 'yellow'), ('b', 'blue'), ('br', 'brown'), ('g', 'green'), ('bl', 'black'), ('w', 'white')], max_length=2, null=True),
        ),
    ]
