# Generated by Django 3.2.8 on 2021-11-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_product_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color',
            new_name='product_color',
        ),
    ]
