# Generated by Django 3.2.8 on 2021-11-15 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.PositiveIntegerField()),
                ('is_verified', models.BooleanField(default=False)),
                ('auth_type', models.CharField(choices=[('phone', 'Phone Number'), ('email', 'Email ID')], max_length=20)),
                ('otp_status', models.CharField(choices=[('delivered', 'Delivered'), ('not_delivered', 'Not Delivered'), ('successful', 'Successful'), ('expired', 'Expired')], max_length=20, verbose_name='OTP Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expired_datetime', models.DateTimeField(verbose_name='Expired At')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customerprofile')),
            ],
            options={
                'verbose_name': '  OTP Management',
                'verbose_name_plural': '  OTP Management',
                'db_table': 'otp_management',
                'ordering': ['-created_at'],
            },
        ),
    ]
