# Generated by Django 3.2.8 on 2021-11-15 05:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('configuration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company_name', models.CharField(max_length=50, unique=True, verbose_name='Company')),
                ('business_nature', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('zip_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message="Zipcode must be entered in the format: '11111'. Up to 5 digits allowed.", regex='^[a-zA-Z0-9]+$'), django.core.validators.MinLengthValidator(3)], verbose_name='Zip Code')),
                ('owner_name', models.CharField(max_length=50, null=True)),
                ('owner_email', models.EmailField(max_length=254, unique=True, verbose_name='Owner Email id')),
                ('company_email_id', models.EmailField(max_length=254, unique=True)),
                ('company_registration_no', models.CharField(max_length=200)),
                ('owner_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{8,15}$')], verbose_name='Owner Mobile No.')),
                ('company_logo', models.FileField(blank=True, null=True, upload_to='company_logo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])], verbose_name='Company logo')),
                ('company_contact_no', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{8,15}$')], verbose_name='Support company Mobile No.')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Support Person Name')),
                ('contact_person_mobile_no', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{8,15}$')], verbose_name='Support Mobile No.')),
                ('contact_person_email_id', models.EmailField(max_length=254, unique=True, verbose_name='Support Email ID')),
                ('billing_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Billing Address')),
                ('website', models.URLField(blank=True, max_length=250, null=True)),
                ('billing_city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='billing_state', chained_model_field='state', db_column='billing_city', limit_choices_to={'is_active': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_city', show_all=True, to='location.citymaster')),
                ('billing_country', models.ForeignKey(blank=True, db_column='billing_country', limit_choices_to={'is_active': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_country', to='location.countrymaster')),
                ('billing_currency', models.ForeignKey(blank=True, limit_choices_to={'is_active': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_currency', to='configuration.currencymaster', verbose_name='Billing Currency')),
                ('billing_state', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='billing_country', chained_model_field='country', db_column='billing_state', limit_choices_to={'is_active': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_state', show_all=True, to='location.statemaster')),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='state', chained_model_field='state', db_column='city', limit_choices_to={'is_active': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_companys', show_all=True, to='location.citymaster')),
                ('country', models.ForeignKey(blank=True, db_column='country', limit_choices_to={'is_active': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_companys', to='location.countrymaster')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', limit_choices_to=models.Q(('is_staff', 0), ('is_superuser', 0), _negated=True), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_companys', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('currency', models.ForeignKey(limit_choices_to={'is_active': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='company_currency', to='configuration.currencymaster', verbose_name='Currency')),
                ('state', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='country', chained_model_field='country', db_column='state', limit_choices_to={'is_active': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_companys', show_all=True, to='location.statemaster')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', limit_choices_to=models.Q(('is_staff', 0), ('is_superuser', 0), _negated=True), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_companys', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': ' Company Master',
                'verbose_name_plural': ' Company Master',
                'db_table': 'company_master',
            },
        ),
    ]
